version: '3'
services:
  sufel:
    image: "giansalex/sufel"
    ports:
      - "8090:80"
    environment:
      - SUFEL_DB_HOST=db
      - SUFEL_DB_DATABASE=sufel_dev
      - SUFEL_DB_PASS=
      - SUFEL_ADMIN=123456
  db:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWOR